### ISSUE TITLE
Torque STDOUT error

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise#69]
when running a [Lisa](https://github.com/MD-Studio/cerise-mdstudio-lisa) specialization I got the following error:
```
[2018-01-09 13:34:54.157] [CRITICAL] Traceback (most recent call last):
  File "cerise/../cerise/back_end/execution_manager.py", line 143, in _process_jobs
    self._stage_and_start_job(job_id, job)
  File "cerise/../cerise/back_end/execution_manager.py", line 100, in _stage_and_start_job
    self._job_runner.start_job(job_id)
  File "cerise/../cerise/back_end/xenon_job_runner.py", line 120, in start_job
    xenon_job = self._x.jobs().submitJob(self._sched, xenon_jobdesc)
jpype._jexception.nl.esciencecenter.xenon.jobs.InvalidJobDescriptionExceptionPyRaisable: nl.esciencecenter.xenon.jobs.InvalidJobDescriptionExcepti
on: torque adaptor: Torque adaptor cannot set STDOUT: a custom STDOUT is set internally

```

**Comment by LourensVeen** [comment]
Made a [Xenon issue](https://github.com/NLeSC/Xenon/issues/601), this is still a problem in Xenon 2. It won't be fixed for Xenon 1 though, so either I'll have to have another shot at the update, or add redirection operators to the command manually rather than using the Xenon interface.

**Comment by LourensVeen** [comment]
The Lisa specialisation is not critical at the moment, so we decided it can wait for a fix in Xenon 2, and a new attempt at upgrading to Xenon 2.

**Comment by LourensVeen** [comment]
Worked around by 97778f565160be8918c8a8723724985ecd5b38e3. Still hoping for a fix in Xenon, but in the mean time things seem to work.
