### ISSUE TITLE
SystemError on running MDStudio workflows with two different specializations

### ISSUE THREAD

**Issue by marcvdijk** [MD-Studio/cerise#80]
After having successfully run a MDStudio LIE workflow using the GT specialization and launching another one using the LISA specialization the latter one fails in the lie_md stage with a Cerise SystemError. The docker container with the LISA specialization is started but there seems to be no connection made to it.
Once the SystemError is raised a workflow using the original GT specialization will also no longer run. The only way to recover seems to be stopping and removing the contains for the specializations.

There may be other factors involved in causing this problem but at least the is the observation I made

**Comment by felipeZ** [comment]
The error is due to this [issue](https://github.com/MD-Studio/lie_md/issues/10) in lie_md

**Comment by LourensVeen** [comment]
Closing this since it's not a Cerise issue.
