### ISSUE TITLE
Non-vital SLURM errors prevent job submission

### ISSUE THREAD

**Issue by marcvdijk** [MD-Studio/cerise#82]
This is a XENON thing and likely to be fixed in Cerulean but for the record.

On the GT cluster, calling any of the SLURM executables gives the following initial error message
after which the program runs normally:

```
squeue: error: NodeNames=node220 Sockets=# and SocketsPerBoard=# is invalid, using SocketsPerBoard
```

Something must we wrong somewhere but jobs can still be submitted and run fine.
However, it seems XENON detects this and stops not submitting any jobs.

If SLURM makes a habit of reporting faulty cluster queue status to the user as `error` that it is likely that XENON will more often refuse to submit jobs ... so it seems.

**Comment by LourensVeen** [comment]
Interesting :). Cerulean checks return values; as long as those are 0 all will be well, but if it returns an error code there then Cerulean will also raise an exception, at which point Cerise will put the job into SystemError.

I agree that it sounds like a Slurm configuration issue, have you contacted the GT admins about this?

I'm not sure what to do about a work-around, just ignoring any errors doesn't sound good, but how would Cerulean detect that this error is harmless and can be ignored?

**Comment by marcvdijk** [comment]
I mailed the GT admins. Waiting for a reply.

I agree this is a difficult scenario to make a work-around for but if it is just a general queue error message for the user the respective executable should still exit with 0 as return value I would say.
Let’s wait what the admins have to say about this.

**Comment by LourensVeen** [comment]
Well, looks like it was a configuration error on the machine, which was promptly fixed. Since there doesn't seem to be much that Cerise could or should do in such a situation (see above), I'm closing this issue.
